# Generated by Django 5.2.10 on 2026-01-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='therapy_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapy.therapyplan'),
        ),
    ]
